### ISSUE TITLE
Cannot use Exporter with the new version of opentelemetry (0.8.0)

### ISSUE THREAD

**Issue by danylaporte** [frigus02/opentelemetry-application-insights#11]
I think the SpanExporter trait has changed between version 0.7 and 0.8.

### Code

```rust
let ex = opentelemetry_application_insights::Exporter::new("..".to_string());
opentelemetry::sdk::Provider::builder().with_simple_exporter(ex);
```

### Output
```bash
31  |         opentelemetry::sdk::Provider::builder().with_simple_exporter(ex);
    |                                                                      ^^ the trait `opentelemetry::exporter::trace::SpanExporter` is not implemented for `opentelemetry_application_insights::Exporter`
    |
```

### Cargo.toml
```toml
[dependencies]
opentelemetry = "0.8"  # <----- works with version 0.7
opentelemetry-application-insights = "0.3.0"
```
