### ISSUE TITLE
method cannot be called on `PipelineBuilder<Client>` due to unsatisfied trait bounds

### ISSUE THREAD

**Issue by preedep** [frigus02/opentelemetry-application-insights#85]
when I build , I've got error "method cannot be called on `PipelineBuilder<Client>` due to unsatisfied trait bounds" at install_batch

```rs
 let _tracer = opentelemetry_application_insights::new_pipeline_from_env()
        .expect("environment variable not found")
        .with_client(reqwest::Client::new())
        .with_live_metrics(true)
        .with_service_name("my-service")
        .install_batch( opentelemetry_sdk::runtime::Tokio);
```

#my dependencies

```toml
opentelemetry = { version = "0.23" , features = ["logs_level_enabled","metrics","trace"] }
opentelemetry_sdk = {version = "0.23", features = ["logs_level_enabled","metrics","trace","rt-tokio","opentelemetry-http"]}
opentelemetry-application-insights = {version = "0.33", features = ["metrics", "live-metrics", "reqwest-client-rustls"]}
reqwest = { version = "0.12", default-features = false,features = ["charset","http2","rustls-tls", "json"] }
```
